ServerTokens Prod
ServerSignature Off
<Directory /var/www/html>
    Options -Indexes
</Directory>
<Directory /var/www/html/wp-content/uploads>
    AllowOverride None
    Options -Indexes -ExecCGI
    <FilesMatch "(?i)\.(php[0-9]*|phtml|pht|phar|cgi|pl|sh)(\.|$)">
        Require all denied
    </FilesMatch>
</Directory>
<FilesMatch "(?i)^(wp-config\.php|\.env|\.git|.*\.(sql|bak|ini|log))$">
    Require all denied
</FilesMatch>
