#!/usr/bin/env bash
source "$(dirname -- "$0")/common.sh"
test "$#" -eq 2 || { echo 'Usage: bash deploy/restore.sh /absolute/backup/path unique-restore-project' >&2; exit 1; }
backup_path="$(cd -- "$1" && pwd)"
target_project="$2"
[[ "$target_project" =~ ^[a-z0-9][a-z0-9_-]*-restore-[a-z0-9_-]+$ ]] || { echo 'Target must contain -restore- and be a new project.' >&2; exit 1; }
test -f "$backup_path/COMPLETE" || { echo 'Incomplete backup refused.' >&2; exit 1; }
(cd "$backup_path" && sha256sum -c SHA256SUMS)
test -z "$(docker ps -aq --filter "label=com.docker.compose.project=$target_project")" || { echo 'Target containers already exist; refusing overwrite.' >&2; exit 1; }
test -z "$(docker volume ls -q --filter "label=com.docker.compose.project=$target_project")" || { echo 'Target volumes already exist; refusing overwrite.' >&2; exit 1; }
# Use only trusted backups generated by backup.sh. Never overwrite a live site.
export COMPOSE_PROJECT_NAME="$target_project" BACKUP_DIR="$backup_path"
dc up -d --wait db
dc run --rm --no-deps archive -c 'test ! -e /var/www/html/wp-config.php && tar -xzf /backup/site.tar.gz -C /var/www/html && chown -R 33:33 /var/www/html'
dc exec -T db sh -c 'MYSQL_PWD="$(cat /run/secrets/db_root_password)" exec mysql -uroot art_alexis' < "$backup_path/database.sql"
echo "Restored data into isolated project: $target_project"
echo 'Website/proxy are NOT started. Match the code release, configure alternate ports/domain, then test before switching traffic.'
echo 'This script did not delete or change the original site.'
